version: 2

sources:
  - name: raw_magalu
    schema: airbyte_schema
    database: AIRBYTE_MAGALU
    description: 
    tables:
      - name: categoria
        columns:
          - name: _airbyte_categoria_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: cidade
        columns:
          - name: _airbyte_cidade_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: cliente
        columns:
          - name: _airbyte_cliente_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: estado
        columns:
          - name: _airbyte_estado_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: filial
        columns:
          - name: _airbyte_filial_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: item_pedido
        columns:
          - name: _airbyte_item_pedido_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: parceiro
        columns:
          - name: _airbyte_parceiro_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: pedido
        columns:
          - name: _airbyte_pedido_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: produto
        columns:
          - name: _airbyte_produto_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: subcategoria
        columns:
          - name: _airbyte_subcategoria_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null



models:
  - name: base_categoria
    config:
      materialized: view  

  - name: base_cidade
    config:
      materialized: view
    columns:
      - name: location_key
        tests:
          - unique
          - not_null

  - name: base_economy
    config:
      materialized: view
    columns:
      - name: location_key
        tests:
          - unique
          - not_null
 
  - name: base_epidemiology
    config:
      tags: ['daily']
      materialized: view
    columns:
      - name: location_key
        tests:
          - relationships:
              to: ref('base_index')
              field: location_key